Repository avaje/avaje-inject, pull requests merged in 2020-11, with the labels that each got.

#66 Add support for method based injection.
  inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
  inject-test/src/test/java/org/example/coffee/fruit/AppleService.java
  inject-test/src/test/java/org/example/request/AController.java
  inject-test/src/test/java/org/example/request/JexController.java
Labels: enhancement

#71 Add io.avaje.inject @PostConstruct/@PreDestroy annotations
  inject-test/src/test/java/org/example/coffee/factory/Configuration.java
  inject/src/main/java/io/avaje/inject/PostConstruct.java
  inject/src/main/java/io/avaje/inject/PreDestroy.java
Labels: enhancement

#73 Add @Priority and make it the default
  inject-test/src/test/java/io/avaje/inject/SystemContextTest.java
  inject-test/src/test/java/org/example/coffee/list/A2Somei.java
  inject-test/src/test/java/org/example/coffee/priority/base/ABasei.java
  inject-test/src/test/java/org/example/coffee/priority/base/BBasei.java
  inject-test/src/test/java/org/example/coffee/priority/base/BaseIface.java
  inject-test/src/test/java/org/example/coffee/priority/base/CBasei.java
  inject-test/src/test/java/org/example/coffee/priority/base/PriorityTest.java
  inject-test/src/test/java/org/example/coffee/priority/custom/AOtheri.java
  inject-test/src/test/java/org/example/coffee/priority/custom/BOtheri.java
  inject-test/src/test/java/org/example/coffee/priority/custom/COtheri.java
  inject-test/src/test/java/org/example/coffee/priority/custom/CustomPriority.java
  inject-test/src/test/java/org/example/coffee/priority/custom/CustomPriorityTest.java
  inject-test/src/test/java/org/example/coffee/priority/custom/OtherIface.java
  inject/src/main/java/io/avaje/inject/Priority.java
  inject/src/main/java/io/avaje/inject/spi/DBeanContext.java
Labels: breaking change

#79 Tidy, no functional change - add finals, suppress rawtypes and dinject to avaje inject
  inject-generator/README.md
  inject-generator/src/main/java/io/avaje/inject/generator/GenericType.java
  inject-generator/src/main/java/io/avaje/inject/generator/GenericTypeParser.java
  inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java
  inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
  inject-generator/src/main/java/io/avaje/inject/generator/Util.java
  inject/README.md
  inject/src/main/java/io/avaje/inject/BeanContextBuilder.java
  inject/src/main/java/io/avaje/inject/BeanEntry.java
  inject/src/main/java/io/avaje/inject/ContextModule.java
  inject/src/main/java/io/avaje/inject/spi/BuilderFactory.java
  inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
  inject/src/main/java/io/avaje/inject/spi/DBuilder.java
  inject/src/main/java/io/avaje/inject/spi/DContextEntry.java
  inject/src/main/java/io/avaje/inject/spi/DContextEntryBean.java
Labels: refactor

#80 Refactor remove BuilderFactory and move newBuilder() methods to Builder interface
  inject-generator/src/main/java/io/avaje/inject/generator/Constants.java
  inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleFactoryWriter.java
  inject/src/main/java/io/avaje/inject/BeanContextBuilder.java
  inject/src/main/java/io/avaje/inject/spi/Builder.java
  inject/src/main/java/io/avaje/inject/spi/BuilderFactory.java
  inject/src/main/java/io/avaje/inject/spi/DBuilder.java
Labels: refactor

#81 Refactor BeanContextBuilder extract interface, use static newBuilder()
  inject-test/src/test/java/io/avaje/inject/BeanContextBuilderTest.java
  inject-test/src/test/java/org/example/coffee/BeanContextBuilderAddTest.java
  inject-test/src/test/java/org/example/coffee/BeanContext_Builder_mockitoSpyTest.java
  inject-test/src/test/java/org/example/coffee/CoffeeMakerTest.java
  inject-test/src/test/java/org/example/coffee/ExtensionExample.java
  inject-test/src/test/java/org/example/coffee/ExtensionExampleTest.java
  inject-test/src/test/java/org/example/coffee/FactoryTest.java
  inject-test/src/test/java/org/example/coffee/InjectListTest.java
  inject-test/src/test/java/org/example/coffee/ProviderTest.java
  inject-test/src/test/java/org/example/coffee/circular/CircularDependencyTest.java
  inject-test/src/test/java/org/example/coffee/factory/AFactTest.java
  inject-test/src/test/java/org/example/coffee/factory/BFactTest.java
  inject-test/src/test/java/org/example/coffee/factory/ConfigurationTest.java
  inject-test/src/test/java/org/example/coffee/factory/MultipleOtherThingsTest.java
  inject-test/src/test/java/org/example/coffee/factory/MyFactoryTest.java
  inject-test/src/test/java/org/example/coffee/fruit/AppleServiceTest.java
  inject-test/src/test/java/org/example/coffee/generic/HazManagerTest.java
  inject-test/src/test/java/org/example/coffee/grind/AMusherTest.java
  inject-test/src/test/java/org/example/coffee/grind/BMusherTest.java
  inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithFieldQualifierTest.java
  inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithNamedTest.java
  inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithQualifierTest.java
  inject-test/src/test/java/org/example/iface/NestedInterfaceTest.java
  inject/src/main/java/io/avaje/inject/BeanContext.java
  inject/src/main/java/io/avaje/inject/BeanContextBuilder.java
  inject/src/main/java/io/avaje/inject/DBeanContextBuilder.java
  inject/src/main/java/io/avaje/inject/SystemContext.java
  inject/src/test/java/io/avaje/inject/BeanContextBuilderTest.java
Labels: breaking change, refactor
