Repository avaje/avaje-inject, pull requests merged in 2024-06, with the labels that each got.

#583 Fix Factory Map generation
  blackbox-test-inject/src/main/java/org/example/myapp/other/ConfigFactory.java
  blackbox-test-inject/src/test/java/org/example/myapp/other/ConfigFactoryTest.java
  inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java
  inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/MetaDataOrdering.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/Util.java
  inject-generator/src/main/java/io/avaje/inject/generator/UtilType.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/ConfigFactory.java
Labels: bug

#596 Remove Duplicate SPI dependency
  inject-generator/pom.xml
Labels: dependencies

#600 Split Events into their own module
  blackbox-aspect/pom.xml
  blackbox-other/pom.xml
  blackbox-other/src/main/java/org/other/one/events/SomeOptionalDep$Publisher.java
  blackbox-test-inject/pom.xml
  blackbox-test-inject/src/main/java/org/example/myapp/events/ExternalEventPublisher.java
  blackbox-test-inject/src/main/java/org/example/myapp/events/ExternalObserver.java
  inject-events/pom.xml
  inject-events/src/main/java/io/avaje/inject/events/Event.java
  inject-events/src/main/java/io/avaje/inject/events/Observer.java
  inject-events/src/main/java/io/avaje/inject/events/ObserverManager.java
  inject-events/src/main/java/io/avaje/inject/events/Observes.java
  inject-events/src/main/java/io/avaje/inject/events/ObservesAsync.java
  inject-events/src/main/java/io/avaje/inject/events/package-info.java
  inject-events/src/main/java/io/avaje/inject/events/spi/DObserverManager.java
  inject-events/src/main/java/io/avaje/inject/events/spi/ObserverManagerPlugin.java
  inject-events/src/main/java/module-info.java
  inject-events/src/test/java/io/avaje/inject/events/events/TestEvent.java
  inject-events/src/test/java/io/avaje/inject/events/events/TestGenericEvent.java
  inject-events/src/test/java/io/avaje/inject/events/spi/DObserverManagerTest.java
  inject-generator/pom.xml
  inject-generator/src/main/java/io/avaje/inject/generator/EventPublisherWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
  inject-generator/src/main/java/io/avaje/inject/generator/FieldReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/ObservesPrism.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/package-info.java
  inject-generator/src/main/java/module-info.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/EventSender.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestGenericObserver.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestObserver.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestObserverInjection.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestQualifiedObserver.java
  inject-gradle-plugin/build.gradle
  inject-maven-plugin/pom.xml
  inject-test/pom.xml
  inject-test/src/main/java/module-info.java
  inject-test/src/test/java/org/example/observes/EventSender.java
  inject-test/src/test/java/org/example/observes/EventSender2.java
  inject-test/src/test/java/org/example/observes/MyObserver.java
  inject-test/src/test/java/org/example/observes/MyObserver2.java
  inject-test/src/test/java/org/example/observes/MyObserverInjected.java
  inject-test/src/test/java/org/example/observes/MyQualifiedObserver.java
  inject-test/src/test/java/org/example/observes/MyStrQualifiedObserver.java
  inject-test/src/test/java/org/example/observes/TestEventMessaging.java
  inject/pom.xml
  inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
  inject/src/main/java/io/avaje/inject/event/package-info.java
  inject/src/main/java/io/avaje/inject/spi/Builder.java
  inject/src/main/java/io/avaje/inject/spi/DBuilder.java
  inject/src/main/java/module-info.java
  jakarta-to-javax.sh
  javax-to-jakarta.sh
  pom.xml
Labels: refactor

#601 Split AOP into a separate module
  blackbox-aspect/src/main/java/module-info.java
  inject-aop/pom.xml
  inject-aop/src/main/java/io/avaje/inject/aop/AOPFallback.java
  inject-aop/src/main/java/io/avaje/inject/aop/Aspect.java
  inject-aop/src/main/java/io/avaje/inject/aop/AspectProvider.java
  inject-aop/src/main/java/io/avaje/inject/aop/Invocation.java
  inject-aop/src/main/java/io/avaje/inject/aop/InvocationException.java
  inject-aop/src/main/java/io/avaje/inject/aop/MethodInterceptor.java
  inject-aop/src/main/java/io/avaje/inject/aop/package-info.java
  inject-aop/src/main/java/module-info.java
  inject-aop/src/test/java/io/avaje/inject/aop/InvocationCallTest.java
  inject-aop/src/test/java/io/avaje/inject/aop/InvocationFallbackRawTest.java
  inject-aop/src/test/java/io/avaje/inject/aop/InvocationFallbackTest.java
  inject-aop/src/test/java/io/avaje/inject/aop/InvocationRunTest.java
  inject-generator/src/main/java/module-info.java
  inject-test/src/main/java/module-info.java
  inject/pom.xml
  inject/src/main/java/module-info.java
  jakarta-to-javax.sh
  javax-to-jakarta.sh
  pom.xml
Labels: refactor

#620 Fix Plugin Service Configuration Error
  blackbox-test-inject/src/main/resources/META-INF/services/io.avaje.inject.spi.InjectExtension
  inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
  inject-generator/src/main/java/io/avaje/inject/generator/LoadServices.java
Labels: bug

#621 Use Avaje Prisms for module-validation
  inject-generator/pom.xml
  inject-generator/src/main/java/io/avaje/inject/generator/InjectProcessor.java
  inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
Labels: refactor

#626 Bump avaje-spi-service dependency to 2.0
  blackbox-test-inject/pom.xml
  inject-generator/pom.xml
Labels: dependencies
