Repository avaje/avaje-inject, pull requests merged in 2024-04, with the labels that each got.

#533 fix: compilation error with providers and `throws`
  blackbox-test-inject/src/main/java/org/example/myapp/config/AppConfig.java
  blackbox-test-inject/src/main/java/org/example/myapp/lazy/LazyFactory.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
Labels: bug

#541 Fix support for @Prototype with Provider<T>
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-test/src/test/java/org/example/coffee/provider/FactoryProvider.java
  inject-test/src/test/java/org/example/coffee/provider/FactoryProviderTest.java
  inject-test/src/test/java/org/example/coffee/provider/ProtoTypeNumberGetter.java
Labels: bug

#498 Support Generic Auto Provides/Requires
  .github/workflows/build.yml
  blackbox-other/src/main/java/org/other/one/OtherComponentGeneric.java
  blackbox-test-inject/pom.xml
  blackbox-test-inject/src/main/java/org/example/myapp/external/HasExternalDependencies.java
  inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/Constants.java
  inject-generator/src/main/java/io/avaje/inject/generator/Dependency.java
  inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/generic/MyConsumerFactory.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/AbstractSuperClass.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/OtherComponent.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/SomeInterface.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/supertypes/SomeInterface2.java
  inject-gradle-plugin/build.gradle
  inject-gradle-plugin/src/main/java/io/avaje/inject/plugin/AvajeInjectPlugin.java
  inject-maven-plugin/pom.xml
  inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java
  inject-test/src/test/java/org/example/custom3/ParentScopeTest.java
  inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
  inject/src/main/java/io/avaje/inject/spi/Module.java
  inject/src/main/java/io/avaje/inject/spi/Plugin.java
  inject/src/test/java/io/avaje/inject/BeanScopeBuilderTest.java
Labels: enhancement

#491 Add something like Jakarta `@Observes`
  inject-generator/src/main/java/io/avaje/inject/generator/BeanReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/EventPublisherWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
  inject-generator/src/main/java/io/avaje/inject/generator/MethodReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/ObservesPrism.java
  inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleBeanWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsInjection.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/package-info.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/CustomEvent.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestGenericObserver.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestObserver.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestObserverInjection.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/observes/TestQualifiedObserver.java
  inject-test/src/test/java/org/example/custom/CustomScopeTest.java
  inject-test/src/test/java/org/example/observes/CustomEvent.java
  inject-test/src/test/java/org/example/observes/MyObserver.java
  inject-test/src/test/java/org/example/observes/MyObserverInjected.java
  inject-test/src/test/java/org/example/observes/MyQualifiedObserver.java
  inject-test/src/test/java/org/example/observes/TestEventMessaging.java
  inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
  inject/src/main/java/io/avaje/inject/DObserverManager.java
  inject/src/main/java/io/avaje/inject/event/ApplicationEvent.java
  inject/src/main/java/io/avaje/inject/event/Event.java
  inject/src/main/java/io/avaje/inject/event/Observer.java
  inject/src/main/java/io/avaje/inject/event/ObserverManager.java
  inject/src/main/java/io/avaje/inject/event/Observes.java
  inject/src/main/java/io/avaje/inject/event/ObservesAsync.java
  inject/src/main/java/io/avaje/inject/event/package-info.java
  inject/src/main/java/io/avaje/inject/spi/Builder.java
  inject/src/main/java/io/avaje/inject/spi/DBuilder.java
  inject/src/main/java/module-info.java
  inject/src/test/java/io/avaje/inject/DObserverManagerTest.java
  inject/src/test/java/io/avaje/inject/events/TestEvent.java
  inject/src/test/java/io/avaje/inject/events/TestGenericEvent.java
Labels: enhancement

#479 Add a switch to determine multi-module wiring order at compile time.
  blackbox-other/src/main/java/org/other/one/SomeOptionalDep.java
  blackbox-other/src/main/java/org/other/one/package-info.java
  blackbox-test-inject/src/main/java/org/example/myapp/Main.java
  blackbox-test-inject/src/main/java/org/example/myapp/config/SomeOptionalDep.java
  blackbox-test-inject/src/main/java/org/example/myapp/config/SomeOptionalUser.java
  blackbox-test-inject/src/main/java/org/example/myapp/config/SomeOptionalUser2.java
  blackbox-test-inject/src/main/java/org/example/myapp/package-info.java
  inject-generator/src/main/java/io/avaje/inject/generator/AvajeModule.java
  inject-generator/src/main/java/io/avaje/inject/generator/ExternalProvider.java
  inject-generator/src/main/java/io/avaje/inject/generator/FactoryOrder.java
  inject-generator/src/main/java/io/avaje/inject/generator/ProcessingContext.java
  inject-generator/src/main/java/io/avaje/inject/generator/Processor.java
  inject-generator/src/main/java/io/avaje/inject/generator/ScopeInfo.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleOrderWriter.java
  inject-generator/src/test/java/io/avaje/inject/generator/ScopeInfoTest.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/_Wiring.java
  inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AutoProvidesMojo.java
  inject-maven-plugin/src/main/java/io/avaje/inject/mojo/AvajeModule.java
  inject/src/main/java/io/avaje/inject/DBeanScopeBuilder.java
  inject/src/main/java/io/avaje/inject/InjectModule.java
  inject/src/main/java/io/avaje/inject/spi/ModuleOrdering.java
  inject/src/main/java/module-info.java
  inject/src/test/java/io/avaje/inject/BeanScopeBuilderTest.java
Labels: enhancement

#548 Qualifiers preserve their case (no longer forced lower case) for BeanEntry and @QualifierMap keys (but still using case insensitive matching for wiring)
  inject-generator/src/main/java/io/avaje/inject/generator/TypeAnnotationReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeExtendsReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/TypeReader.java
  inject-generator/src/main/java/io/avaje/inject/generator/Util.java
  inject-generator/src/test/java/io/avaje/inject/generator/InjectProcessorTest.java
  inject-test/src/main/java/io/avaje/inject/test/MetaReader.java
  inject-test/src/test/java/org/example/coffee/CoffeeMakerTest.java
  inject-test/src/test/java/org/example/coffee/InjectListTest.java
  inject-test/src/test/java/org/example/coffee/qualifier/StoreManagerWithNamedTest.java
  inject-test/src/test/java/org/example/custom/CustomScopeTest.java
  inject-test/src/test/java/org/example/injectextension/WithExtnNamedSpyTest.java
  inject/src/main/java/io/avaje/inject/spi/DBeanMap.java
  inject/src/main/java/io/avaje/inject/spi/DContextEntryBean.java
  inject/src/main/java/io/avaje/inject/spi/EnrichBean.java
  inject/src/main/java/io/avaje/inject/spi/KeyUtil.java
Labels: breaking change, reason-for-version-bump
