Repository avaje/avaje-inject, pull requests merged in 2025-04, with the labels that each got.

#791 [generator] Make aop/events `requires static`
  inject-generator/pom.xml
  inject-generator/src/main/java/module-info.java
Labels: dependencies

#792 [test] remove hard dependency on events
  inject-test/pom.xml
Labels: bug

#795 Fix duplicate short names in Module Generation
  blackbox-test-inject/src/main/java/org/example/myapp/duplicate/SameType.java
  blackbox-test-inject/src/main/java/org/example/myapp/duplicate/two/SameType.java
  blackbox-test-inject/src/test/java/org/example/myapp/duplicate/SameTypeTest.java
  inject-generator/src/main/java/io/avaje/inject/generator/MetaData.java
  inject-generator/src/main/java/io/avaje/inject/generator/SimpleModuleWriter.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/duplicate/SameType.java
  inject-generator/src/test/java/io/avaje/inject/generator/models/valid/duplicate/two/SameType.java
Labels: bug

#810 Support Inherited Lifecycle on Factory Methods
  blackbox-test-inject/src/main/java/org/example/myapp/lifecycle/GreetingService.java
  blackbox-test-inject/src/main/java/org/example/myapp/lifecycle/ServiceCreator.java
  blackbox-test-inject/src/test/java/org/example/myapp/lifecycle/HelloServiceTest.java
  blackbox-test-inject/src/test/java/org/example/myapp/lifecycle/TestBeanFactory.java
  inject-generator/src/main/java/io/avaje/inject/generator/AnnotationUtil.java
Labels: enhancement

#812 #811 @InjectTest field Lookup, fix use field.getDeclaringClass();
  inject-test/src/main/java/io/avaje/inject/test/Lookups.java
  inject-test/src/main/java/io/avaje/inject/test/MetaReader.java
  inject-test/src/test/java/org/example/inherit/MyOneAbstract.java
  inject-test/src/test/java/org/example/inherit/MyOneTest.java
  inject-test/src/test/java/org/example/inherit/sub/MySubAbstract.java
Labels: bug
